// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-E3b51Gf3D0EM7DDTD0irJUxELCWZ2Zk',
    appId: '1:101326510851:web:2e722286838b130d6a6736',
    messagingSenderId: '101326510851',
    projectId: 'my-e-commercial-app-55aa1',
    authDomain: 'my-e-commercial-app-55aa1.firebaseapp.com',
    storageBucket: 'my-e-commercial-app-55aa1.firebasestorage.app',
    measurementId: 'G-ZZBZJG6SNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhHUCjnJeS04qDB-VvPN0ojrqGaaD__7w',
    appId: '1:101326510851:android:59af46ed15fda68c6a6736',
    messagingSenderId: '101326510851',
    projectId: 'my-e-commercial-app-55aa1',
    storageBucket: 'my-e-commercial-app-55aa1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZWM3ESom_i0Z8QfohBJxogvaLawd40Cg',
    appId: '1:101326510851:ios:52ae64f74f5494f36a6736',
    messagingSenderId: '101326510851',
    projectId: 'my-e-commercial-app-55aa1',
    storageBucket: 'my-e-commercial-app-55aa1.firebasestorage.app',
    iosBundleId: 'com.example.finalFruitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZWM3ESom_i0Z8QfohBJxogvaLawd40Cg',
    appId: '1:101326510851:ios:52ae64f74f5494f36a6736',
    messagingSenderId: '101326510851',
    projectId: 'my-e-commercial-app-55aa1',
    storageBucket: 'my-e-commercial-app-55aa1.firebasestorage.app',
    iosBundleId: 'com.example.finalFruitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-E3b51Gf3D0EM7DDTD0irJUxELCWZ2Zk',
    appId: '1:101326510851:web:56d734bad05582686a6736',
    messagingSenderId: '101326510851',
    projectId: 'my-e-commercial-app-55aa1',
    authDomain: 'my-e-commercial-app-55aa1.firebaseapp.com',
    storageBucket: 'my-e-commercial-app-55aa1.firebasestorage.app',
    measurementId: 'G-33VR5H55J2',
  );
}
